### ISSUE TITLE
:bug: 특정 기간동안 태깅 로그가 2번씩 저장되었던 문제

### ISSUE THREAD

**Issue by niamu01** [innovationacademy-kr/24hane-backend#152]
## Symptom
- 릴리스 데이터베이스에 22년 08월 20일~23년 02월 09일의 모든 로그가 2번씩 저장되어 있습니다!
- 미싱 태그 로그를 표시하게 되면서 작업해야 할 것 중 하나에 추가하게 되었습니다.

## How To Solve
- 중복 데이터를 제거하는 쿼리문 사용하기?

**Comment by joohongpark** [comment]
일단은 로직상에서 중복 데이터를 제거하도록 바꿨습니다.
오버헤드가 좀 생길거 같지만, 사용자 경험상 잘못된 데이터가 들어가는거 같아 일단 이렇게 조치했으며
sql에서 `distinct` 문법을 사용하면 RDB에서 가져올 때 중복을 가져올 수도 있지만
현재는 인덱스도 같이 가져오기 때문에 해당 문법을 사용하기에 무리가 있는거 같아 이렇게 조치했습니다.
